const EditorsActionTypes = {
  FETCH_EDITORS_START: "FETCH_EDITORS_START",
  FETCH_EDITORS_SUCCESS: "FETCH_EDITORS_SUCCESS",
  FETCH_EDITORS_FAILURE: "FETCH_EDITORS_FAILURE",
}

export default EditorsActionTypes
