const ArticlesActionTypes = {
  FETCH_ARTICLES_START: "FETCH_ARTICLES_START",
  FETCH_ARTICLES_SUCCESS: "FETCH_ARTICLES_SUCCESS",
  FETCH_ARTICLES_FAILURE: "FETCH_ARTICLES_FAILURE",
}

export default ArticlesActionTypes
